from PyQt5 import QtCore, QtGui, QtWidgets
from edit_functions import Edit


class InsertDialog(object):
        def setupUi(self, Dialog):
                Dialog.setObjectName("Dialog")
                Dialog.resize(410, 711)
                self.Dialog = Dialog
                font = QtGui.QFont()
                font.setPointSize(10)
                Dialog.setFont(font)
                self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
                self.buttonBox.setGeometry(QtCore.QRect(40, 670, 341, 32))
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
                self.buttonBox.setSizePolicy(sizePolicy)
                self.buttonBox.setLayoutDirection(QtCore.Qt.RightToLeft)
                self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
                self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply)
                self.buttonBox.setCenterButtons(True)
                self.buttonBox.setObjectName("buttonBox")
                self.verticalGroupBox = QtWidgets.QGroupBox(Dialog)
                self.verticalGroupBox.setGeometry(QtCore.QRect(50, 100, 311, 241))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.verticalGroupBox.setFont(font)
                self.verticalGroupBox.setStyleSheet("background-color: rgb(229, 229, 229);\n"
                "")
                self.verticalGroupBox.setObjectName("verticalGroupBox")
                self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalGroupBox)
                self.verticalLayout.setObjectName("verticalLayout")
                self.label_11 = QtWidgets.QLabel(self.verticalGroupBox)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.label_11.setFont(font)
                self.label_11.setAlignment(QtCore.Qt.AlignCenter)
                self.label_11.setObjectName("label_11")
                self.verticalLayout.addWidget(self.label_11)
                self.frame = QtWidgets.QFrame(self.verticalGroupBox)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.frame.setFont(font)
                self.frame.setObjectName("frame")
                self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
                self.horizontalLayout.setObjectName("horizontalLayout")
                self.label = QtWidgets.QLabel(self.frame)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.label.setFont(font)
                self.label.setAlignment(QtCore.Qt.AlignCenter)
                self.label.setObjectName("label")
                self.horizontalLayout.addWidget(self.label)
                self.lineEdit = QtWidgets.QLineEdit(self.frame)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
                self.lineEdit.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.lineEdit.setFont(font)
                self.lineEdit.setObjectName("lineEdit")
                self.horizontalLayout.addWidget(self.lineEdit)
                self.verticalLayout.addWidget(self.frame)
                self.frame1 = QtWidgets.QFrame(self.verticalGroupBox)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.frame1.setFont(font)
                self.frame1.setObjectName("frame1")
                self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame1)
                self.horizontalLayout_2.setObjectName("horizontalLayout_2")
                self.label_2 = QtWidgets.QLabel(self.frame1)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.label_2.setFont(font)
                self.label_2.setStyleSheet("border-color: rgb(0, 0, 0);")
                self.label_2.setAlignment(QtCore.Qt.AlignCenter)
                self.label_2.setObjectName("label_2")
                self.horizontalLayout_2.addWidget(self.label_2)
                self.lineEdit_2 = QtWidgets.QLineEdit(self.frame1)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
                self.lineEdit_2.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.lineEdit_2.setFont(font)
                self.lineEdit_2.setObjectName("lineEdit_2")
                self.horizontalLayout_2.addWidget(self.lineEdit_2)
                self.verticalLayout.addWidget(self.frame1)
                self.frame2 = QtWidgets.QFrame(self.verticalGroupBox)
                self.frame2.setObjectName("frame2")
                self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame2)
                self.horizontalLayout_4.setObjectName("horizontalLayout_4")
                self.label_5 = QtWidgets.QLabel(self.frame2)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.label_5.setFont(font)
                self.label_5.setAlignment(QtCore.Qt.AlignCenter)
                self.label_5.setObjectName("label_5")
                self.horizontalLayout_4.addWidget(self.label_5)
                self.lineEdit_3 = QtWidgets.QLineEdit(self.frame2)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
                self.lineEdit_3.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.lineEdit_3.setFont(font)
                self.lineEdit_3.setObjectName("lineEdit_3")
                self.horizontalLayout_4.addWidget(self.lineEdit_3)
                self.verticalLayout.addWidget(self.frame2)
                self.frame3 = QtWidgets.QFrame(self.verticalGroupBox)
                self.frame3.setObjectName("frame3")
                self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame3)
                self.horizontalLayout_5.setObjectName("horizontalLayout_5")
                self.label_6 = QtWidgets.QLabel(self.frame3)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
                self.label_6.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.label_6.setFont(font)
                self.label_6.setAlignment(QtCore.Qt.AlignCenter)
                self.label_6.setObjectName("label_6")
                self.horizontalLayout_5.addWidget(self.label_6)
                self.lineEdit_5 = QtWidgets.QLineEdit(self.frame3)
                self.lineEdit_5.setEnabled(True)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
                self.lineEdit_5.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.lineEdit_5.setFont(font)
                self.lineEdit_5.setObjectName("lineEdit_5")
                self.horizontalLayout_5.addWidget(self.lineEdit_5)
                self.verticalLayout.addWidget(self.frame3)
                self.verticalGroupBox_2 = QtWidgets.QGroupBox(Dialog)
                self.verticalGroupBox_2.setGeometry(QtCore.QRect(50, 410, 311, 241))
                self.verticalGroupBox_2.setStyleSheet("background-color: rgb(229, 229, 229);\n"
                "\n"
                "")
                self.verticalGroupBox_2.setObjectName("verticalGroupBox_2")
                self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalGroupBox_2)
                self.verticalLayout_2.setObjectName("verticalLayout_2")
                self.label_12 = QtWidgets.QLabel(self.verticalGroupBox_2)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.label_12.setFont(font)
                self.label_12.setAlignment(QtCore.Qt.AlignCenter)
                self.label_12.setObjectName("label_12")
                self.verticalLayout_2.addWidget(self.label_12)
                self.frame4 = QtWidgets.QFrame(self.verticalGroupBox_2)
                self.frame4.setObjectName("frame4")
                self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame4)
                self.horizontalLayout_6.setObjectName("horizontalLayout_6")
                self.label_3 = QtWidgets.QLabel(self.frame4)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.label_3.setFont(font)
                self.label_3.setAlignment(QtCore.Qt.AlignCenter)
                self.label_3.setObjectName("label_3")
                self.horizontalLayout_6.addWidget(self.label_3)
                self.lineEdit_6 = QtWidgets.QLineEdit(self.frame4)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
                self.lineEdit_6.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.lineEdit_6.setFont(font)
                self.lineEdit_6.setObjectName("lineEdit_6")
                self.horizontalLayout_6.addWidget(self.lineEdit_6)
                self.verticalLayout_2.addWidget(self.frame4)
                self.frame_2 = QtWidgets.QFrame(self.verticalGroupBox_2)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.frame_2.setFont(font)
                self.frame_2.setObjectName("frame_2")
                self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_2)
                self.horizontalLayout_7.setObjectName("horizontalLayout_7")
                self.label_7 = QtWidgets.QLabel(self.frame_2)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.label_7.setFont(font)
                self.label_7.setStyleSheet("border-color: rgb(0, 0, 0);")
                self.label_7.setAlignment(QtCore.Qt.AlignCenter)
                self.label_7.setObjectName("label_7")
                self.horizontalLayout_7.addWidget(self.label_7)
                self.comboBox_2 = QtWidgets.QComboBox(self.frame_2)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.comboBox_2.setFont(font)
                self.comboBox_2.setObjectName("comboBox_2")
                self.comboBox_2.addItem("")
                self.comboBox_2.addItem("")
                self.comboBox_2.addItem("")
                self.comboBox_2.addItem("")
                self.horizontalLayout_7.addWidget(self.comboBox_2)
                self.verticalLayout_2.addWidget(self.frame_2)
                self.frame_4 = QtWidgets.QFrame(self.verticalGroupBox_2)
                self.frame_4.setObjectName("frame_4")
                self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_4)
                self.horizontalLayout_9.setObjectName("horizontalLayout_9")
                self.label_9 = QtWidgets.QLabel(self.frame_4)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.label_9.setFont(font)
                self.label_9.setAlignment(QtCore.Qt.AlignCenter)
                self.label_9.setObjectName("label_9")
                self.horizontalLayout_9.addWidget(self.label_9)
                self.comboBox = QtWidgets.QComboBox(self.frame_4)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.comboBox.setFont(font)
                self.comboBox.setObjectName("comboBox")
                self.comboBox.addItem("")
                self.comboBox.addItem("")
                self.comboBox.addItem("")
                self.comboBox.addItem("")
                self.horizontalLayout_9.addWidget(self.comboBox)
                self.verticalLayout_2.addWidget(self.frame_4)
                self.frame_3 = QtWidgets.QFrame(self.verticalGroupBox_2)
                self.frame_3.setObjectName("frame_3")
                self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_3)
                self.horizontalLayout_8.setObjectName("horizontalLayout_8")
                self.label_8 = QtWidgets.QLabel(self.frame_3)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.label_8.setFont(font)
                self.label_8.setAlignment(QtCore.Qt.AlignCenter)
                self.label_8.setObjectName("label_8")
                self.horizontalLayout_8.addWidget(self.label_8)
                self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_3)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.lineEdit_8.sizePolicy().hasHeightForWidth())
                self.lineEdit_8.setSizePolicy(sizePolicy)
                self.lineEdit_8.setMaximumSize(QtCore.QSize(268, 16777215))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.lineEdit_8.setFont(font)
                self.lineEdit_8.setObjectName("lineEdit_8")
                self.horizontalLayout_8.addWidget(self.lineEdit_8)
                self.verticalLayout_2.addWidget(self.frame_3)
                self.frame5 = QtWidgets.QFrame(Dialog)
                self.frame5.setGeometry(QtCore.QRect(50, 50, 311, 41))
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(30)
                sizePolicy.setHeightForWidth(self.frame5.sizePolicy().hasHeightForWidth())
                self.frame5.setSizePolicy(sizePolicy)
                self.frame5.setObjectName("frame5")
                self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame5)
                self.horizontalLayout_10.setObjectName("horizontalLayout_10")
                self.label_10 = QtWidgets.QLabel(self.frame5)
                self.label_10.setAlignment(QtCore.Qt.AlignCenter)
                self.label_10.setObjectName("label_10")
                self.horizontalLayout_10.addWidget(self.label_10)
                self.radioButton = QtWidgets.QRadioButton(self.frame5)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.radioButton.sizePolicy().hasHeightForWidth())
                self.radioButton.setSizePolicy(sizePolicy)
                self.radioButton.setText("")
                self.radioButton.setObjectName("radioButton")
                self.horizontalLayout_10.addWidget(self.radioButton)
                self.groupBox = QtWidgets.QGroupBox(Dialog)
                self.groupBox.setGeometry(QtCore.QRect(50, 360, 311, 38))
                self.groupBox.setStyleSheet("background-color: rgb(229, 229, 229);")
                self.groupBox.setObjectName("groupBox")
                self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
                self.horizontalLayout_3.setObjectName("horizontalLayout_3")
                self.label_4 = QtWidgets.QLabel(self.groupBox)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.label_4.setFont(font)
                self.label_4.setAlignment(QtCore.Qt.AlignCenter)
                self.label_4.setObjectName("label_4")
                self.horizontalLayout_3.addWidget(self.label_4)
                self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
                self.lineEdit_4.setSizePolicy(sizePolicy)
                self.lineEdit_4.setMaximumSize(QtCore.QSize(268, 16777215))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.lineEdit_4.setFont(font)
                self.lineEdit_4.setObjectName("lineEdit_4")
                self.horizontalLayout_3.addWidget(self.lineEdit_4)
                self.frame6 = QtWidgets.QFrame(Dialog)
                self.frame6.setGeometry(QtCore.QRect(30, -10, 361, 61))
                self.frame6.setObjectName("frame6")
                self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame6)
                self.verticalLayout_3.setObjectName("verticalLayout_3")
                self.label_13 = QtWidgets.QLabel(self.frame6)
                self.label_13.setAlignment(QtCore.Qt.AlignCenter)
                self.label_13.setObjectName("label_13")
                self.verticalLayout_3.addWidget(self.label_13)
                self.label_14 = QtWidgets.QLabel(self.frame6)
                self.label_14.setAlignment(QtCore.Qt.AlignCenter)
                self.label_14.setObjectName("label_14")
                self.verticalLayout_3.addWidget(self.label_14)
                self.retranslateUi(Dialog)
                self.buttonBox.clicked.connect(self.insertSender)
                self.buttonBox.rejected.connect(Dialog.reject)
                QtCore.QMetaObject.connectSlotsByName(Dialog)

        def insertSender(self):
                self.insert = Edit(radioButton1=self.radioButton.isChecked(), embg=self.lineEdit_4.text(),
                                   currency=str(self.comboBox_2.currentText()),
                                   bank_product=str(self.comboBox.currentText()),
                                   balance=self.lineEdit_8.text(), account_number=self.lineEdit_6.text(),
                                   first_name=self.lineEdit.text(), last_name=self.lineEdit_2.text(),
                                   birthdate=self.lineEdit_3.text(), address=self.lineEdit_5.text())
                self.insert = self.insert.new()
                if self.insert:
                        self.showMessageBox('Successful', 'Successfully added')
                        self.Dialog.close()
                else:
                        self.showMessageBox('Warning', 'Invalid EMBG or account number')


        def showMessageBox(self, title, message):
                msgBox = QtWidgets.QMessageBox()
                msgBox.setIcon(QtWidgets.QMessageBox.Warning)
                msgBox.setWindowTitle(title)
                msgBox.setText(message)
                msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
                msgBox.exec_()


        def retranslateUi(self, Dialog):
                _translate = QtCore.QCoreApplication.translate
                Dialog.setWindowTitle(_translate("Dialog", "Insert"))
                self.label_11.setText(_translate("Dialog", "Client details:"))
                self.label.setText(_translate("Dialog", "First name:"))
                self.label_2.setText(_translate("Dialog", "Last name:"))
                self.label_5.setText(_translate("Dialog", "Birthdate:"))
                self.label_6.setText(_translate("Dialog", "Address:"))
                self.label_12.setText(_translate("Dialog", "Account details:"))
                self.label_3.setText(_translate("Dialog", "Account number:"))
                self.label_7.setText(_translate("Dialog", "Currency:"))
                self.comboBox_2.setItemText(0, _translate("Dialog", "EUR"))
                self.comboBox_2.setItemText(1, _translate("Dialog", "MKD"))
                self.comboBox_2.setItemText(2, _translate("Dialog", "USD"))
                self.comboBox_2.setItemText(3, _translate("Dialog", "CHF"))
                self.label_9.setText(_translate("Dialog", "Bank product:"))
                self.comboBox.setItemText(0, _translate("Dialog", "Current account"))
                self.comboBox.setItemText(1, _translate("Dialog", "Term deposit"))
                self.comboBox.setItemText(2, _translate("Dialog", "Savings account"))
                self.comboBox.setItemText(3, _translate("Dialog", "Loans"))
                self.label_8.setText(_translate("Dialog", "Balance:"))
                self.label_10.setText(_translate("Dialog", "Is it a new client?"))
                self.label_4.setText(_translate("Dialog", "EMBG:"))
                self.label_13.setText(_translate("Dialog", "If it is a new client check that button and fill in everything."))
                self.label_14.setText(_translate("Dialog", " Otherwise, fill in just the EMBG and account details."))