from PyQt5 import QtCore, QtGui, QtWidgets
from insert_window import InsertDialog
from update_window import UpdateDialog
from delete_window import DeleteDialog
from view_window import DataGrid
from search_window import SearchDialog


class mainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(596, 333)
        self.mainWindow = MainWindow
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.gridGroupBox.setGeometry(QtCore.QRect(70, 80, 451, 161))
        self.gridGroupBox.setStyleSheet("background-color: rgb(229, 229, 229);")
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.gridGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalGroupBox_2 = QtWidgets.QGroupBox(self.gridGroupBox)
        self.verticalGroupBox_2.setStyleSheet("")
        self.verticalGroupBox_2.setObjectName("verticalGroupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalGroupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.verticalGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.verticalGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_2.addWidget(self.pushButton_8)
        self.gridLayout.addWidget(self.verticalGroupBox_2, 0, 0, 1, 1)
        self.verticalGroupBox_3 = QtWidgets.QGroupBox(self.gridGroupBox)
        self.verticalGroupBox_3.setObjectName("verticalGroupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalGroupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalGroupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalGroupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.insertShow)
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalGroupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalGroupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.deleteShow)
        self.verticalLayout_3.addWidget(self.pushButton_5)
        self.gridLayout.addWidget(self.verticalGroupBox_3, 0, 2, 1, 1)
        self.verticalGroupBox = QtWidgets.QGroupBox(self.gridGroupBox)
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.gridLayout.addWidget(self.verticalGroupBox, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(160, 60, 47, 13))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 302, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        MainWindow.setCentralWidget(self.centralwidget)
        MainWindow.sender()
        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.searchShow)
        self.pushButton_2.clicked.connect(self.searchShow)
        self.pushButton_3.clicked.connect(self.insertShow)
        self.pushButton_4.clicked.connect(self.updateShow)
        self.pushButton_5.clicked.connect(self.deleteShow)
        self.pushButton_6.clicked.connect(self.viewShow)
        self.pushButton_7.clicked.connect(self.viewShow)
        self.pushButton_8.clicked.connect(self.viewShow)
        self.pushButton_9.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def viewShow(self):
        self.sender = self.mainWindow.sender()
        self.viewWindow = DataGrid(buttonClicked=self.sender.text())
        self.viewWindow.show()

    def deleteShow(self):
        self.Dialog = QtWidgets.QDialog()
        self.ui = DeleteDialog()
        self.ui.setupUi(self.Dialog)
        self.Dialog.show()

    def updateShow(self):
        self.Dialog = QtWidgets.QDialog()
        self.ui = UpdateDialog()
        self.ui.setupUi(self.Dialog)
        self.Dialog.show()

    def insertShow(self):
        self.Dialog = QtWidgets.QDialog()
        self.ui = InsertDialog()
        self.ui.setupUi(self.Dialog)
        self.Dialog.show()

    def searchShow(self):
        self.searchWindow = QtWidgets.QDialog()
        self.searchUI = SearchDialog()
        self.sender = self.mainWindow.sender()
        self.searchUI.setupUi(self.searchWindow, buttonClicked=self.sender.text())
        self.searchWindow.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bank"))
        self.label_2.setText(_translate("MainWindow", "View:"))
        self.pushButton_6.setText(_translate("MainWindow", "Clients"))
        self.pushButton_7.setText(_translate("MainWindow", "Accounts"))
        self.pushButton_8.setText(_translate("MainWindow", "Client/accounts"))
        self.label_3.setText(_translate("MainWindow", "Edit:"))
        self.pushButton_3.setText(_translate("MainWindow", "Insert new client/account"))
        self.pushButton_4.setText(_translate("MainWindow", "Update client/account"))
        self.pushButton_5.setText(_translate("MainWindow", "Delete client/account"))
        self.label.setText(_translate("MainWindow", "Search by:"))
        self.pushButton.setText(_translate("MainWindow", "EMBG"))
        self.pushButton_2.setText(_translate("MainWindow", "Account number"))
        self.pushButton_9.setText(_translate("MainWindow", "Log out"))
